;;; import-baseline.el --- One-time, non-evaluating baseline import -*- lexical-binding: t; -*-
;; Run with emacs -Q --batch -l tools/import-baseline.el from the OLD config root.
;; Source Lisp is READ, never LOADed. Existing generated files are not overwritten.
(require 'cl-lib)
(require 'pp)
(defvar lc-import-root (expand-file-name "lazy-emacs/" default-directory))
(defun lc-import-forms (file)
  (with-temp-buffer
    (insert-file-contents file) (goto-char (point-min))
    (let (forms)
      (condition-case nil
          (while t (forward-comment (point-max))
                 (let ((line (line-number-at-pos)))
                   (push (cons line (read (current-buffer))) forms)))
        (end-of-file nil))
      (nreverse forms))))
(defun lc-import-write (name text &optional private)
  (let ((file (expand-file-name name lc-import-root)))
    (unless (file-exists-p file)
      (make-directory (file-name-directory file) t)
      (with-temp-file file (insert text))
      (when private (set-file-modes file #o600)))))
(defun lc-import-transform (form)
  (cond ((and (consp form) (eq (car form) 'expand-file-name)
              (stringp (cadr form)) (string-prefix-p "~/" (cadr form))
              (null (cddr form)))
         (list 'lc-home-file (substring (cadr form) 2)))
        ((equal form '(concat org-directory "notes.org"))
         '(expand-file-name "notes.org" org-directory))
        ((consp form) (cons (lc-import-transform (car form))
                            (lc-import-transform (cdr form))))
        (t form)))
(let* ((init (lc-import-forms "init.el"))
       (custom (lc-import-forms "custom.el"))
       (vars (make-hash-table :test #'eq)) faces private)
  (dolist (entry init)
    (let ((form (cdr entry)))
      (pcase (car-safe form)
        ('custom-set-variables
         (dolist (quoted (cdr form))
           (let* ((spec (cadr quoted)) (name (car spec)))
             (cond ((eq name 'canlock-password) (push spec private))
                   ((or (string-match-p "\\`\\(?:kiwix\\|ebdb\\|gptel\\|xenops\\|claude-code\\|canlock\\)" (symbol-name name))
                        (memq name '(dtrt-indent-global-mode lsp-rust-analyzer-rustc-source
                                     org-ditaa-jar-path org-ditaa-java-exec org-babel-ditaa-java-cmd))) nil)
                   (t (puthash name (cadr spec) vars))))))
        ('custom-set-faces (setq faces (mapcar #'cadr (cdr form)))))))
  ;; Safe, explicitly selected top-level preference assignments, not arbitrary source code.
  (let ((retain '(org-todo-keywords org-columns-default-format org-capture-templates
                  org-tag-alist org-todo-state-tags-triggers org-tag-faces
                  org-agenda-skip-deadline-if-done org-agenda-custom-commands
                  org-log-done org-return-follows-link org-hide-emphasis-markers
                  org-src-tab-acts-natively org-src-fontify-natively org-startup-folded
                  org-startup-with-inline-images scroll-preserve-screen-position
                  python-shell-completion-native-disabled-interpreters request-backend
                  el-job--debug-level geiser-mode-auto-p code-cells-convert-ipynb-style)))
    (dolist (entry custom)
      (let ((form (cdr entry)))
        (when (eq (car-safe form) 'setq)
          (let ((pairs (cdr form)))
            (while pairs
              (when (memq (car pairs) retain)
                (puthash (car pairs) (cadr pairs) vars))
              (setq pairs (cddr pairs))))))))
  (dolist (pair '((LaTeX-command . "lualatex") (TeX-engine . 'luatex)
                 (org-confirm-babel-evaluate . t) (org-directory . (lc-home-file "doc/org"))
                 (org-default-notes-file . (lc-home-file "doc/org/notes.org"))
                 (org-noter-notes-search-path . (list (lc-home-file "doc/org-roam")))
                 (org-agenda-files . (list (lc-home-file "doc/org-agenda")))
                 (org-agenda-file-regexp . "\\`[^.].*\\.org\\'")
                 (org-mem-watch-dirs . (list (lc-home-file "doc/org-roam/")))
                 (org-mem-do-sync-with-org-id . t)
                 (org-node-creation-fn . #'org-capture) (org-node-alter-candidates . t)
                 (org-modern-hide-stars . nil) (org-modern-table . nil)
                 (org-modern-list . '((?* . "•") (?+ . "‣")))
                 (backup-by-copying . t) (backup-directory-alist . (list (cons "." (lc-home-file "backup/"))))
                 (delete-old-versions . t) (kept-new-versions . 6) (kept-old-versions . 2)
                 (version-control . t) (tab-always-indent . 'complete)
                 (word-wrap . t) (cua-auto-tabify-rectangles . nil) (cua-keep-region-after-copy . t)
                 (tool-bar-button-margin . '(7 . 1)) (visible-bell . t) (line-spacing . 0.2)
                 (scroll-conservatively . 101) (scroll-margin . 0)
                 (compilation-scroll-output . t) (ansi-color-for-compilation-mode . t)
                 (read-process-output-max . 1048576) (jit-lock-defer-time . 0.05)
                 (doc-view-resolution . 300) (treemacs-width . 25)
                 (which-key-idle-delay . 0.2) (company-idle-delay . 0.5)
                 (completion-styles . '(orderless basic)) (completion-category-defaults . nil)
                 (completion-category-overrides . '((file (styles basic partial-completion))))
                 (register-preview-delay . 0.5) (consult-narrow-key . "<")
                 (lsp-rust-analyzer-cargo-watch-command . "clippy")
                 (lsp-eldoc-render-all . t) (lsp-idle-delay . 0.6) (lsp-inlay-hint-enable . t)
                 (lsp-rust-analyzer-display-lifetime-elision-hints-enable . "skip_trivial")
                 (lsp-rust-analyzer-display-chaining-hints . t)
                 (lsp-rust-analyzer-display-lifetime-elision-hints-use-parameter-names . nil)
                 (lsp-rust-analyzer-display-closure-return-type-hints . t)
                 (lsp-rust-analyzer-display-parameter-hints . nil)
                 (lsp-rust-analyzer-display-reborrow-hints . nil)
                 (lsp-enable-suggest-server-download . nil)
                 (lsp-ui-peek-always-show . t) (lsp-ui-sideline-show-hover . t)
                 (lsp-ui-doc-enable . t) (lsp-ui-doc-show-with-mouse . t)
                 (lsp-tex-server . 'digestif) (dap-python-debugger . 'debugpy)
                 (rust-mode-treesitter-derive . t) (rustic-lsp-client . 'lsp-mode)
                 (rustic-format-on-save . nil) (rust-format-on-save . nil)
                 (format-all-debug . nil) (format-all-show-errors . 'errors)
                 (outline-indent-ellipsis . " ▼ ")
                 (indent-bars-no-descend-lists . t) (indent-bars-treesit-support . t)
                 (indent-bars-treesit-ignore-blank-lines-types . '("module"))
                 (indent-bars-treesit-scope . '((python function_definition class_definition for_statement if_statement with_statement while_statement)))
                 (proced-enable-color-flag . t) (proced-tree-flag . t)
                 (proced-auto-update-flag . 'visible) (proced-auto-update-interval . 1)
                 (proced-descent . t) (proced-filter . 'user)
                 (flymake-show-diagnostics-at-end-of-line . t) (flymake-indicator-type . 'margins)
                 (flymake-margin-indicators-string . '((error "!" compilation-error) (warning "?" compilation-warning) (note "i" compilation-info)))
                 (eshell-history-size . 100000) (eshell-save-history-on-exit . t)
                 (eshell-hist-ignoredups . t) (eat-term-name . "xterm-256color")
                 (recentf-max-menu-items . 25) (auth-source-save-behavior . nil)
                 (epa-pinentry-mode . 'loopback) (pulsar-face . 'pulsar-blue)
                 (TeX-electric-sub-and-superscript . t) (lc-indent-detection . t)
                 (dirvish-attributes . '(vc-state subtree-state nerd-icons collapse git-msg file-time file-size))
                 (agent-shell-header-style . 'text) (agent-shell-session-restore-verbosity . 'full)
                 (agent-shell-preferred-agent-config . '(preselect . loki))))
    (puthash (car pair) (cdr pair) vars))
  ;; Import prior exact manifest trust, not broad directory trust.
  (puthash 'lc-guix-authorized-manifests (gethash 'buffer-env-safe-files vars) vars)
  ;; Caption/name fixes are safe preferences, not source evaluation.
  (setq faces (cl-subst :slant :italic faces))
  (let (entries)
    (maphash (lambda (name expr)
               (push (list name (lc-import-transform expr)) entries)) vars)
    (setq entries (sort entries (lambda (a b) (string-lessp (symbol-name (car a)) (symbol-name (car b))))))
    (lc-import-write
     "defaults.el"
     (concat ";;; defaults.el --- Migrated preferences; seed for Customize -*- lexical-binding: t; -*-\n"
             ";; Generated by tools/import-baseline.el; source config was never evaluated.\n"
             "(custom-set-variables\n"
             (mapconcat (lambda (entry) (concat " '" (pp-to-string entry))) entries "") ")\n"
             (concat "(custom-set-faces\n" (mapconcat (lambda (entry) (concat " '" (pp-to-string entry))) faces "") ")\n"))))
  (lc-import-write "private.el"
                   (concat ";;; private.el --- Local-only news credential -*- lexical-binding: t; -*-\n"
                           "(custom-set-variables\n" (mapconcat (lambda (entry) (concat " '" (pp-to-string entry))) private "") ")\n") t)
  ;; Copy data/definitions only, to purpose-built modules; no source startup loads.
  (dolist (selection '(("lisp/lc-org-data.el" 921 1132)
                       ("lisp/lc-org-series.el" 1291 1332)
                       ("lisp/lc-autoinsert-data.el" 1362 1441)))
    (let (forms)
      (dolist (entry custom)
        (when (<= (nth 1 selection) (car entry) (nth 2 selection))
          (let ((form (cdr entry)))
            (when (or (memq (car-safe form) '(defun define-auto-insert))
                      (and (equal (car-safe form) 'setq)
                           (eq (cadr form) 'org-node-series-defs)))
              (push (lc-import-transform form) forms)))))
      (lc-import-write
       (car selection)
       (concat (format ";;; %s --- Retained definitions/data -*- lexical-binding: t; -*-\n(require 'lc-core)\n" (car selection))
               (mapconcat #'pp-to-string (nreverse forms) "\n")
               (format "\n(provide '%s)\n" (file-name-base (car selection))))))))
