;; Guix owns packages; local modified Org/Wakib/Elfeed Tube sources take precedence.
(use-modules (guix profiles))
(specifications->manifest
 '("emacs-pgtk" "mu" "font-dejavu" "maxima"
   "emacs-org-notify" "emacs-org-node" "emacs-org-mem" "emacs-org-modern"
   "emacs-org-modern-indent" "emacs-org-contrib" "emacs-org-super-agenda"
   "emacs-org-sticky-header" "emacs-mixed-pitch" "emacs-inheritenv"
   "emacs-org-noter" "emacs-org-pdftools" "emacs-org-download" "emacs-org-mime" "emacs-org-msg"
   "emacs-agent-shell" "emacs-acp" "emacs-shell-maker"
   "emacs-vertico" "emacs-marginalia" "emacs-orderless" "emacs-company"
   "emacs-consult" "emacs-embark" "emacs-wgrep"
   "emacs-spacious-padding" "emacs-solarized-theme" "emacs-pulsar" "emacs-ultra-scroll"
   "emacs-bar-cursor" "emacs-popper" "emacs-nerd-icons"
   "emacs-jinx" "emacs-yasnippet" "emacs-tempel" "emacs-smartparens"
   "emacs-rainbow-delimiters" "emacs-comment-tags" "emacs-outshine" "emacs-form-feed"
   "emacs-outline-indent" "emacs-indent-bars" "emacs-dtrt-indent" "emacs-format-all-the-code"
   "emacs-capf-autosuggest" "emacs-vlf" "emacs-eat"
   "emacs-projectile" "emacs-back-button" "emacs-buffer-env" "emacs-envrc"
   "emacs-treemacs" "emacs-treemacs-nerd-icons" "emacs-lsp-treemacs"
   "emacs-magit" "emacs-forge" "emacs-fj" "emacs-pr-review" "emacs-guix"
   "emacs-rust-mode" "emacs-rustic" "emacs-pyvenv" "emacs-jedi" "emacs-flycheck"
   "emacs-lsp-mode" "emacs-lsp-ui" "emacs-ccls" "emacs-dap-mode" "emacs-vhdl-ext"
   "emacs-web-mode" "emacs-mmm-mode" "emacs-js2-mode" "emacs-typescript-mode"
   "emacs-yaml-mode" "emacs-go-mode" "emacs-julia-mode" "emacs-julia-snail"
   "emacs-code-cells" "emacs-jupyter" "emacs-slime" "emacs-arei" "emacs-geiser"
   "emacs-gnuplot" "emacs-auctex"
   "emacs-pdf-tools" "emacs-saveplace-pdf-view" "emacs-nov" "emacs-dirvish" "emacs-dired-launch"
   "emacs-trashed" "emacs-osm" "emacs-wttrin" "emacs-debbugs"
   "emacs-emms" "emacs-org-emms" "emacs-mediainfo-mode" "emacs-elfeed" "emacs-mpv"
   "emacs-request" "emacs-el-job"
   "git" "ripgrep" "python" "aspell-dict-en" "aspell-dict-de"))
