;;; lc-editing.el --- Editing policies activated by matching buffers -*- lexical-binding: t; -*-
(require 'lc-core)
(require 'use-package)
(defgroup lc-editing nil "Shared buffer policies." :group 'lazy-config)
(defcustom lc-variable-pitch-modes '(org-mode rustic-mode treemacs-mode nxml-mode js-base-mode
                                              css-mode html-mode mhtml-mode python-base-mode)
  "Modes using variable pitch. Fixed-pitch programming defaults otherwise remain."
  :type '(repeat symbol) :group 'lc-editing)
(defun lc-pitch-buffer ()
  (when (apply #'derived-mode-p lc-variable-pitch-modes) (variable-pitch-mode 1)))
(defun lc-media-text (_mime data) (insert (decode-coding-string data 'utf-8)))
(defun lc-register-text-paste ()
  (yank-media-handler "text/plain;charset=utf-8" #'lc-media-text))
(defun lc-paste (&optional arg)
  "Use clipboard MIME support without breaking vanilla yank or its prefix arguments."
  (interactive "*P")
  (if (and (null arg) (display-graphic-p)
           (gui-backend-selection-exists-p 'CLIPBOARD))
      (yank-media)
    (yank arg)))
(put 'lc-paste 'delete-selection 'yank)
(defun lc-delete-file-and-buffer ()
  (interactive)
  (unless buffer-file-name (user-error "Not a file-visiting buffer"))
  (when (yes-or-no-p (format "Delete %s%s and its buffer? " buffer-file-name
                            (if (buffer-modified-p) " (including unsaved changes)" "")))
    (delete-file buffer-file-name delete-by-moving-to-trash)
    (set-buffer-modified-p nil) (kill-buffer (current-buffer))))
(defun lc-other-window-mru ()
  (interactive) (select-window (get-mru-window nil nil t)))
(defun lc-formatting-setup ()
  "One generic format-on-save path; VHDL uses its native beautifier."
  (unless (derived-mode-p 'vhdl-mode 'vhdl-ts-mode)
    (when (require 'format-all nil t)
      (condition-case err
          (progn (format-all-ensure-formatter) (format-all-mode 1))
        (user-error (display-warning 'lazy-config
                                     (format "Formatter unavailable for %s: %s"
                                             major-mode (error-message-string err))))))))
(defun lc-vhdl-formatting-setup ()
  (remove-hook 'before-save-hook #'format-all-buffer t)
  (add-hook 'before-save-hook #'vhdl-beautify-buffer nil t))
(defun lc-detect-indentation ()
  (when (and lc-indent-detection (require 'dtrt-indent nil t)) (dtrt-indent-mode 1)))
(defun lc-autoinsert ()
  (require 'autoinsert)
  (require 'lc-autoinsert-data)
  (let ((auto-insert 'other) (auto-insert-query nil)) (auto-insert)))
(use-package jinx :ensure nil
  :hook ((text-mode prog-mode conf-mode) . jinx-mode)
  :bind (("M-$" . jinx-correct) ("C-M-$" . jinx-languages)))
(use-package yasnippet :ensure nil :hook ((prog-mode text-mode) . yas-minor-mode)
  :config
  (let ((directory (lc-home-file "src/guix/etc/snippets/yas")))
    (when (file-directory-p directory) (add-to-list 'yas-snippet-dirs directory)))
  (yas-reload-all))
(use-package tempel :ensure nil :commands (tempel-complete tempel-insert)
  :config
  (unless (listp tempel-path) (setq tempel-path (list tempel-path)))
  (let ((directory (lc-home-file "src/guix/etc/snippets/tempel")))
    (when (file-directory-p directory)
      (add-to-list 'tempel-path (expand-file-name "*.eld" directory)))))
(use-package smartparens-config :ensure nil :defer t)
(use-package smartparens :ensure nil :hook ((scheme-mode emacs-lisp-mode) . smartparens-mode)
  :config (require 'smartparens-config))
(use-package rainbow-delimiters :ensure nil :hook (prog-mode . rainbow-delimiters-mode))
(use-package comment-tags :ensure nil :hook (prog-mode . comment-tags-mode))
(use-package outshine :ensure nil :hook (emacs-lisp-mode . outshine-mode))
(use-package form-feed :ensure nil
  :hook ((prog-mode org-mode) . form-feed-mode))
(use-package outline-indent :ensure nil :hook ((python-base-mode yaml-mode yaml-ts-mode) . outline-indent-minor-mode))
(use-package indent-bars :ensure nil :hook ((python-base-mode yaml-mode yaml-ts-mode) . indent-bars-mode))
(use-package format-all :ensure nil :commands (format-all-mode format-all-ensure-formatter format-all-buffer))
(use-package capf-autosuggest :ensure nil :hook ((comint-mode eshell-mode) . capf-autosuggest-mode))
(use-package vlf-setup :ensure nil :defer t)
(use-package eat :ensure nil :after eshell :demand t
  :config (eat-eshell-mode 1) (eat-eshell-visual-command-mode 1))
(use-package proced :ensure nil :commands proced)
(use-package trashed :ensure nil :commands trashed
  :config (setq trashed-action-confirmer 'y-or-n-p trashed-use-header-line t
                trashed-sort-key '("Date deleted" . t) trashed-date-format "%Y-%m-%d %H:%M:%S"))
(use-package osm :ensure nil :commands osm)
(use-package wttrin :ensure nil :commands wttrin)
(defun eshell/e (&rest files)
  "Open FILES in Emacs from Eshell."
  (if (member "--help" files) (message "e FILE [FILE ...]")
    (unless files (user-error "Usage: e FILE [FILE ...]"))
    (dolist (file files) (find-file file))))
(put 'eshell/e 'eshell-no-numeric-conversions t)
(defun eshell/nd (&rest args)
  "Create a directory and parents, then cd into it; -v enables feedback."
  (if (or (member "--help" args) (member "-h" args)) (message "nd [-v] DIRECTORY")
    (let* ((verbose (or (member "-v" args) (member "--verbose" args)))
           (names (cl-remove-if (lambda (s) (member s '("-v" "--verbose"))) args)))
      (unless (= (length names) 1) (user-error "Usage: nd [-v] DIRECTORY"))
      (let ((dir (car names)))
        (if (file-exists-p dir) (message "Directory already exists: %s" dir)
          (make-directory dir t) (when verbose (message "Created %s" dir)))
        (eshell/cd dir)))))
(put 'eshell/nd 'eshell-no-numeric-conversions t)
(defun lc-eshell-setup ()
  (setq-local completion-styles '(basic partial-completion) tab-always-indent 'complete)
  (keymap-local-set "M-r" #'consult-history))
(add-hook 'eshell-mode-hook #'lc-eshell-setup)
(defun lc-start-editing ()
  (require 'wakib-keys) (wakib-keys 1)
  (cua-mode 1) (transient-mark-mode 1)
  (global-prettify-symbols-mode 1)
  (keymap-set wakib-keys-overriding-map "C-f" #'consult-line)
  (keymap-set wakib-keys-overriding-map "C-q" #'quoted-insert)
  (keymap-set wakib-keys-overriding-map "<escape>" #'keyboard-escape-quit)
  (require 'yank-media)
  (add-hook 'after-change-major-mode-hook #'lc-register-text-paste 90)
  (lc-register-text-paste)
  (keymap-global-set "<remap> <yank>" #'lc-paste)
  (keymap-global-set "C-y" #'undo-redo)
  (keymap-global-set "C-a" #'mark-whole-buffer)
  (keymap-global-set "C-s" #'save-buffer) (keymap-global-set "C-S-s" #'save-buffer)
  (keymap-global-set "<f2>" #'save-buffer) (keymap-global-set "<f3>" #'find-file)
  (keymap-global-set "C-<f3>" #'find-file-at-point)
  (keymap-global-set "M-<f3>" #'ff-find-other-file)
  (keymap-global-set "s-<delete>" #'lc-delete-file-and-buffer)
  (keymap-global-set "M-o" #'lc-other-window-mru)
  (keymap-global-set "C-M-<next>" #'forward-page)
  (keymap-global-set "C-M-<prior>" #'backward-page)
  (keymap-global-set "C-M-<down>" #'forward-sexp)
  (keymap-set emacs-lisp-mode-map "C-<down-mouse-1>" #'xref-find-definitions-at-mouse)
  (add-hook 'after-change-major-mode-hook #'lc-pitch-buffer)
  (add-hook 'prog-mode-hook #'display-line-numbers-mode)
  (add-hook 'prog-mode-hook #'lc-detect-indentation)
  (add-hook 'prog-mode-hook #'lc-formatting-setup 80)
  (add-hook 'text-mode-hook #'visual-line-mode)
  (add-hook 'find-file-hook #'lc-autoinsert)
  (add-hook 'vhdl-mode-hook #'lc-vhdl-formatting-setup 90)
  (add-hook 'vhdl-ts-mode-hook #'lc-vhdl-formatting-setup 90)
  (require 'uniquify) (setq uniquify-buffer-name-style 'forward)
  (save-place-mode 1) (recentf-mode 1)
  ;; VLF setup installs the large-file entry advice, not the VLF UI itself.
  (when (require 'vlf-setup nil t))
  (dolist (area '(mode-line left-margin left-fringe right-fringe header-line
                           vertical-scroll-bar tool-bar menu-bar))
    (keymap-global-set (format "<%s> <mouse-movement>" area) #'ignore)))
(provide 'lc-editing)
