;;; lc-org.el --- Eager reminders/index, lazy Org integrations -*- lexical-binding: t; -*-
(require 'lc-core)
(require 'lc-ui)
(require 'use-package)
(defvar org-agenda-files)
(defvar org-mem-watch-dirs)
(defvar my-org-header (concat "#+DATE: %<%Y-%m-%d>\n#+AUTHOR: " user-full-name
                             "\n#+FILETAGS: :internal:\n\n%?"))
(defgroup lc-org nil "Reminders, notes and safe execution." :group 'lazy-config)
(defcustom lc-babel-languages '(shell ditaa python latex jupyter dot gnuplot plantuml)
  "Babel backends available on first execution, without eager backend loading."
  :type '(repeat symbol) :group 'lc-org)
(defcustom lc-org-preview-on-display t
  "Enable the local automatic preview in displayed Org buffers, not background scanners."
  :type 'boolean :group 'lc-org)
(defun lc-org-setup ()
  (org-indent-mode 1) (mixed-pitch-mode 1) (text-scale-set 1)
  (setq-local line-move-visual nil)
  (when (require 'org-sticky-header nil t) (org-sticky-header-mode 1))
  (keymap-set org-mode-map "<home>" #'move-beginning-of-line)
  (keymap-set org-mode-map "<end>" #'move-end-of-line)
  (dolist (key '("M-<left>" "C-S-<left>" "C-S-<right>" "S-<up>" "S-<down>"))
    (keymap-unset org-mode-map key))
  (keymap-set org-mode-map "C-c <up>" #'org-priority-up)
  (keymap-set org-mode-map "C-c <down>" #'org-priority-down)
  (keymap-set org-mode-map "C-c l" #'org-insert-link)
  (keymap-set org-mode-map "C-c C-g C-r" #'org-shiftmetaright)
  (keymap-unset org-mode-map "<remap> <move-beginning-of-line>")
  (keymap-unset org-mode-map "<remap> <move-end-of-line>")
  (setq-local org-outline-regexp "\\*+ \\|\f"))
(defun lc-org-preview-display (frame)
  (when (and lc-org-preview-on-display (lc-input-frame-p frame))
    (dolist (window (window-list frame 'no-minibuffer))
      (with-current-buffer (window-buffer window)
        (when (and (derived-mode-p 'org-mode) (not (bound-and-true-p org-latex-preview-mode)))
          (lc-require 'org-latex-preview) (org-latex-preview-mode 1))))))
(defun lc-register-babel-autoloads ()
  "Declare Org's public execution functions without loading every backend.
Babel calls org-babel-execute:LANGUAGE after its normal confirmation. Loading
ob-jupyter registers the installed kernels' further language aliases itself."
  (dolist (language lc-babel-languages)
    (let* ((jupyter (eq language 'jupyter))
           (library (format "ob-%s" language))
           (execution-languages (if jupyter '(jupyter-python jupyter-julia jupyter-R) (list language))))
      (dolist (execution-language execution-languages)
        (let ((command (intern (format "org-babel-execute:%s" execution-language))))
          (unless (fboundp command) (autoload command library nil nil)))))))
(defun lc-org-is-spelling-region ()
  (interactive)
  (let ((ispell-skip-region-alist
         (append ispell-skip-region-alist
                 '((":PROPERTIES:" . ":END:") ("~" . "~") ("=" . "=")
                   ("#\\+BEGIN_SRC" . "#\\+END_SRC")))))
    (ispell-buffer)))
(defalias 'endless/org-ispell #'lc-org-is-spelling-region)
(use-package org :ensure nil :mode ("\\.org\\'" . org-mode)
  :commands (org-agenda org-capture org-store-link)
  :bind (("C-c m" . org-store-link) ("C-c a" . org-agenda) ("C-c c" . org-capture))
  :config
  (require 'lc-org-data)
  (add-hook 'org-mode-hook #'lc-org-setup)
  (add-hook 'window-buffer-change-functions #'lc-org-preview-display)
  (lc-register-babel-autoloads)
  ;; Correct initialization and environment propagation, including TRAMP processes.
  (lc-require 'inheritenv)
  (advice-add 'org-babel-execute-src-block :around #'inheritenv-apply))
(use-package org-modern :ensure nil :hook ((org-mode . org-modern-mode) (org-agenda-finalize . org-modern-agenda)))
(use-package org-modern-indent :ensure nil :hook (org-mode . org-modern-indent-mode))
(use-package mixed-pitch :ensure nil :commands mixed-pitch-mode)
(use-package org-download :ensure nil :hook (dired-mode . org-download-enable))
(use-package org-super-agenda :ensure nil :after org-agenda :demand t
  :config (org-super-agenda-mode 1))
(use-package org-contrib :ensure nil :after org :demand t :config (require 'org-checklist))
(use-package org-node :ensure nil :commands (org-node-find org-node-grep org-node-capture-target)
  :bind (("C-<Search>" . org-node-find) ("M-<Search>" . org-node-grep))
  :config
  (add-hook 'org-mode-hook #'org-node-backlink-mode)
  (add-hook 'org-node-creation-hook #'org-node-put-created)
  (add-hook 'org-open-at-point-functions #'org-node-try-visit-ref-node))
(use-package org-node-backlink :ensure nil :commands org-node-backlink-mode)
(use-package org-node-seq :ensure nil :commands org-node-seq-dispatch
  :bind ("C-M-s" . org-node-seq-dispatch)
  :config (org-node-seq-mode 1))
(use-package ox-publish :ensure nil :commands (org-publish org-publish-project))
(use-package pandoc-mode :ensure nil :commands pandoc-mode)
(use-package org-mime :ensure nil :commands org-mime-htmlize)
(use-package org-msg :ensure nil :commands org-msg-mode)
(defun lc-stop-org-services ()
  "Stop this configuration's background services using their public controls."
  (when (fboundp 'org-notify-stop) (org-notify-stop))
  (when (fboundp 'org-node-cache-mode) (org-node-cache-mode -1))
  (when (fboundp 'org-mem-updater-mode) (org-mem-updater-mode -1)))
(defun lc-start-org-services ()
  "These user-requested services run during daemon initialization, even headless."
  (lc-require 'org)
  (unless (string-prefix-p (file-truename (lc-file "vendor/org/lisp/"))
                           (file-truename (locate-library "org")))
    (error "Mixed Org installation: the local Org tree must take precedence"))
  (require 'org-protocol)
  (lc-require 'org-notify)
  (unless (advice-member-p #'lc-global-env-call 'org-notify-process)
    (advice-add 'org-notify-process :around #'lc-global-env-call))
  (org-notify-start)
  (lc-require 'org-node) (lc-require 'org-mem-updater)
  (org-mem-updater-mode 1) (org-node-cache-mode 1))
(lc-action 'store-link "Store link" #'org-store-link "org-store-link" "Store a link to this location")
(lc-action 'node-find "Find note" #'org-node-find "org-node-find" "Find an Org node")
(lc-action 'node-grep "Search notes" #'org-node-grep "org-node-grep" "Search Org nodes")
(lc-action 'agenda "Agenda" #'org-agenda "org-agenda" "Show the agenda")
(provide 'lc-org)
