;;; lc-programming.el --- Language entry points and debugger policy -*- lexical-binding: t; -*-
(require 'lc-core)
(require 'use-package)
(defgroup lc-programming nil "Language services and formatting." :group 'lazy-config)
(defcustom lc-tree-sitter-remaps
  '((sh-mode bash-ts-mode bash) (c-mode c-ts-mode c) (c++-mode c++-ts-mode cpp)
    (clojure-mode clojure-ts-mode clojure) (css-mode css-ts-mode css)
    (go-mode go-ts-mode go) (go-mod-mode go-mod-ts-mode gomod) (java-mode java-ts-mode java)
    (javascript-mode js-ts-mode javascript) (js-json-mode json-ts-mode json)
    (typescript-mode tsx-ts-mode tsx) (vhdl-mode vhdl-ts-mode vhdl) (yaml-mode yaml-ts-mode yaml))
  "Records (CLASSIC-MODE TREE-SITTER-MODE GRAMMAR).
Install a remap only when the target command and its grammar are available."
  :type '(repeat (list (symbol :tag "Classic mode") (symbol :tag "Tree-sitter mode")
                      (symbol :tag "Grammar"))) :group 'lc-programming)
(defun lc-treesit-remap ()
  (when (require 'treesit nil t)
    (let ((dir (lc-home-file ".guix-home/profile/lib/tree-sitter/")))
      (when (file-directory-p dir) (add-to-list 'treesit-extra-load-path dir)))
    (dolist (entry lc-tree-sitter-remaps)
      (pcase-let ((`(,classic-mode ,tree-sitter-mode ,grammar) entry))
        (when (and (fboundp tree-sitter-mode) (treesit-ready-p grammar t))
          (setf (alist-get classic-mode major-mode-remap-alist) tree-sitter-mode))))))
(lc-treesit-remap)
(defun lc-prettify-program ()
  (let* ((operators '(("<=" . ?≤) (">=" . ?≥) ("==" . ?⩵) ("=" . ?≝)
                      ("&&" . ?∧) ("||" . ?∨) ("!" . ?¬) ("*" . ?·)))
         (items
          (cond ((derived-mode-p 'scheme-mode) '(("lambda" . ?λ)))
                ((derived-mode-p 'python-base-mode)
                 '(("in" . ?∈) ("True" . ?⊨) ("False" . ?⊭) ("is" . ?≡) ("is not" . ?≢)
                   ("__add__" . ?+) ("__sub__" . ?-) ("__mul__" . ?*) ("__mod__" . ?%)
                   ("__truediv__" . ?/) ("__floordiv__" . "//")
                   ("__gt__" . ?>) ("__ge__" . ?≥) ("__lt__" . ?<) ("__le__" . ?≤)
                   ("__eq__" . ?=) ("__ne__" . ?≠) ("issubset" . ?⊆) ("issuperset" . ?⊇)))
                ((derived-mode-p 'rust-mode 'rust-ts-mode 'rustic-mode)
                 (append operators '(("!=" . ?≠) ("add" . ?+) ("sub" . ?-) ("mul" . ?*)
                                     ("div" . ?/) ("not" . ?!) ("gt" . ?>) ("ge" . ?≥)
                                     ("lt" . ?<) ("le" . ?≤) ("eq" . ?=) ("ne" . ?≠))))
                ((derived-mode-p 'c-ts-mode) (append operators '(("!=" . ?≠) ("void" . ?⊥) ("->" . ?→))))
                ((derived-mode-p 'c++-ts-mode) (append operators '(("void" . ?⊥) ("->" . ?→)))))))
    (when items (setq-local prettify-symbols-alist (append items prettify-symbols-alist))
          (prettify-symbols-mode 1))))
(add-hook 'after-change-major-mode-hook #'lc-prettify-program)
;; The public rust-mode option in gui-settings.el is evaluated before this library
;; chooses its parent. No mode-function patch or per-buffer interception is needed.
(use-package rust-mode :ensure nil :defer t)
(use-package rustic :ensure nil :mode ("\\.rs\\'" . rustic-mode)
  :config (add-to-list 'auto-mode-alist '("\\.rs\\'" . rustic-mode)))
(use-package pyvenv :ensure nil :commands (pyvenv-activate pyvenv-deactivate pyvenv-mode))
(use-package eglot :ensure nil :hook (python-base-mode . eglot-ensure)
  :config (add-to-list 'eglot-server-programs '(rust-mode "rust-analyzer")))
(use-package jedi :ensure nil :commands jedi:setup)
(use-package flycheck :ensure nil :commands flycheck-mode)
(use-package flymake :ensure nil :hook (emacs-lisp-mode . flymake-mode))
(use-package lsp-mode :ensure nil :commands (lsp lsp-deferred)
  :hook (vhdl-ts-mode . lsp-deferred)
  :config
  (add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration)
  (add-hook 'lsp-mode-hook #'lsp-ui-mode)
  ;; A ccls executable is not clangd. Register the correct client instead.
  (when (require 'ccls nil t) (add-to-list 'lsp-disabled-clients 'clangd)))
(use-package lsp-ui :ensure nil :commands lsp-ui-mode)
(use-package ccls :ensure nil :after lsp-mode :defer t)
(use-package web-mode :ensure nil
  :mode ("\\.\\(?:phtml\\|tpl\\.php\\|[agj]sp\\|as[cp]x\\|erb\\|mustache\\|djhtml\\|html?\\)\\'" . web-mode))
(defun genehack-vue-mode ()
  "Vue major mode with one selected LSP client, not two competing servers."
  (interactive)
  (lc-require 'web-mode)
  (web-mode)
  (setq major-mode 'genehack-vue-mode mode-name "ghVue")
  (lc-require 'lsp-mode) (lc-require 'lsp-volar)
  (add-to-list 'lsp-disabled-clients 'vls)
  (lsp-deferred))
(put 'genehack-vue-mode 'derived-mode-parent 'web-mode)
(add-to-list 'auto-mode-alist '("\\.vue\\'" . genehack-vue-mode))
(use-package mmm-mode :ensure nil :mode ("\\.php\\'" . html-mode)
  :config (require 'mmm-auto) (setq mmm-global-mode 'maybe)
  (mmm-add-mode-ext-class 'html-mode "\\.php\\'" 'html-php))
(use-package js2-mode :ensure nil :mode ("\\.js\\'" . js2-mode))
(use-package typescript-mode :ensure nil :mode ("\\.ts\\'" . typescript-mode))
(use-package yaml-mode :ensure nil :mode ("\\.ya?ml\\'" . yaml-mode))
(use-package go-mode :ensure nil :mode ("\\.go\\'" . go-mode))
(use-package julia-mode :ensure nil :mode ("\\.jl\\'" . julia-mode))
(use-package julia-snail :ensure nil :hook (julia-mode . julia-snail-mode))
(use-package python-django :ensure nil :commands python-django-open-project)
(use-package ssass-mode :ensure nil :mode ("\\.sass\\'" . ssass-mode))
(use-package code-cells :ensure nil :hook (python-base-mode . code-cells-mode-maybe)
  :config
  (add-hook 'emacs-lisp-mode-hook (lambda () (setq-local outline-regexp ";\\{3,\\}")))
  (add-hook 'python-base-mode-hook (lambda () (setq-local outline-regexp "#\\{2,\\}"))))
;; Current Guix Jupyter already uses start-file-process for remote port allocation;
;; retain its implementation and public jupyter-executable option, not the old override.
(use-package jupyter :ensure nil :commands (jupyter-run-repl jupyter-connect-repl))
(use-package slime :ensure nil :commands slime :config (slime-setup '(slime-fancy slime-quicklisp slime-asdf)))
(use-package arei :ensure nil :hook (scheme-mode . arei-mode) :commands arei)
(use-package geiser :ensure nil :commands run-geiser)
(use-package gnuplot :ensure nil :mode ("\\.\\(?:gp\\|plot\\)\\'" . gnuplot-mode))
(use-package tex :ensure nil :mode ("\\.tex\\'" . LaTeX-mode)
  :config (add-hook 'LaTeX-mode-hook #'TeX-fold-mode))
(autoload 'maxima-mode "maxima" nil t)
(autoload 'maxima "maxima" nil t)
(autoload 'imaxima "imaxima" nil t)
(autoload 'imath-mode "imath" nil t)
(add-to-list 'auto-mode-alist '("\\.\\(?:mac\\|max\\)\\'" . maxima-mode))
(use-package vhdl-ext :ensure nil :hook (vhdl-ts-mode . vhdl-ext-mode)
  :init (setq vhdl-ext-feature-list '(font-lock hierarchy lsp beautify navigation template
                                             imenu which-func hideshow time-stamp ports))
  :config (vhdl-ext-mode-setup))
(use-package dap-mode :ensure nil :commands (dap-debug dap-breakpoint-toggle)
  :config
  (require 'dap-python)
  (require 'lc-dap-gdb)
  (dap-register-debug-template
   "Python :: Attach" (list :type "python" :request "attach" :connect '(:host "127.0.0.1" :port 5678)
                            :name "Python :: Attach" :cwd "${workspaceFolder}"
                            :env (list :PYTHONPATH "${workspaceFolder}") :console "integratedTerminal"))
  (tooltip-mode 1))
(defun lc-debug-command (gud dap)
  (cond ((bound-and-true-p gud-minor-mode) (call-interactively gud))
        ((and (featurep 'dap-mode) (bound-and-true-p dap-mode))
         (if dap (call-interactively dap) (user-error "No DAP equivalent")))
        (t (user-error "No debugger active"))))
;; Debug dispatch records are (KEY GUD-COMMAND DAP-COMMAND); nil means that
;; backend has no equivalent action, not a reason to silently do something else.
(dolist (entry '(("C-<f7>" gud-print dap-eval) ("C-<f3>" gud-refresh dap-switch-stack-frame)
                 ("C-<f2>" gud-kill-buffer dap-disconnect) ("C-<f8>" gud-break dap-breakpoint-toggle)
                 ("C-b" gud-break dap-breakpoint-toggle) ("<f5>" gud-break dap-breakpoint-toggle)
                 ("<f11>" gud-step dap-step-in) ("<f10>" gud-next dap-next)
                 ("C-<f10>" gud-nexti nil) ("<f8>" gud-cont dap-continue)
                 ("C-<f11>" gud-watch dap-ui-expressions-add) ("C-<f4>" gud-jump nil)
                 ("<?>" gud-remove nil) ("<f4>" gud-until nil)))
  (pcase-let ((`(,key ,gud-command ,dap-command) entry))
    (define-key prog-mode-map (kbd key)
      (lambda () (interactive) (lc-debug-command gud-command dap-command)))))
(keymap-global-set "<f5>" #'dap-breakpoint-toggle)
(provide 'lc-programming)
