;;; test-core.el --- Path, process and frame policy regression tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
;; C-subr mocks must not compile/load trampolines through mocked filesystem calls.
(setq native-comp-enable-subr-trampolines nil)
(defvar lc-test-root (expand-file-name "../" (file-name-directory load-file-name)))
(setq lc-config-root lc-test-root)
(add-to-list 'load-path (expand-file-name "lisp" lc-test-root))
(add-to-list 'load-path (expand-file-name "user-lisp" lc-test-root))
(require 'lc-core)
(require 'lc-security)
(require 'lc-frames)
(require 'lc-git-commit)
(require 'lc-guix-build)
(ert-deftest lc-real-home-is-independent-of-buffer-env ()
  (let ((lc-real-home "/home/real/") (process-environment '("HOME=/tmp/project")))
    (should (equal (lc-home-file "doc/org") "/home/real/doc/org"))))
(ert-deftest lc-no-manifest-no-fallback ()
  (let ((default-directory (make-temp-file "lc-work-" t)))
    (unwind-protect (should-error (lc--manifest) :type 'user-error)
      (delete-directory default-directory t))))
(ert-deftest lc-workspace-is-not-symlinked-recipe-directory ()
  (let* ((workspace (make-temp-file "/tmp/lc-workspace-" t))
         (recipe (make-temp-file "/tmp/lc-shared-recipe-" nil ".scm"))
         (default-directory (file-name-as-directory workspace)))
    (unwind-protect
        (progn
          (make-symbolic-link recipe (expand-file-name "manifest.scm" workspace))
          (should (equal (lc-workspace-root) (file-name-as-directory workspace)))
          (should (equal (lc--manifest) (file-truename recipe))))
      (delete-directory workspace t) (delete-file recipe))))
(ert-deftest lc-unapproved-manifest-does-not-launch ()
  (let ((file (make-temp-file "lc-manifest-")) (lc-guix-authorized-manifests nil))
    (unwind-protect
        (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) nil)))
          (should-error (lc-authorize-manifest file) :type 'user-error))
      (delete-file file))))
(ert-deftest lc-approval-hash-invalidated ()
  (let ((file (make-temp-file "lc-manifest-")))
    (unwind-protect
        (let ((lc-guix-authorized-manifests (list (cons file (lc--manifest-hash file)))))
          (with-temp-file file (insert "changed"))
          (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) nil)))
            (should-error (lc-authorize-manifest file))))
      (delete-file file))))
(ert-deftest lc-agent-default-mounts-and-explicit-secrets ()
  (let ((lc-agent-share-host-emacs nil) (lc-agent-share-tmp nil)
        (lc-agent-program-directories nil) (lc-agent-extra-shares nil) (lc-agent-extra-exposes nil))
    (cl-letf (((symbol-function 'executable-find) (lambda (_) "/bin/guix"))
              ((symbol-function 'lc--manifest) (lambda () "/work/manifest.scm"))
              ((symbol-function 'lc-workspace-root) (lambda () "/work/"))
              ((symbol-function 'lc-authorize-manifest) (lambda (_) "hash"))
              ((symbol-function 'lc--manifest-hash) (lambda (_) "hash")))
      (let ((command (lc-guix-command 'agent)))
        (should (member "--container" command)) (should (member "--pure" command))
        (should (member "--preserve=^OPENAI_API_KEY$" command))
        (should-not (member "--share=/tmp" command))
        (should (equal (seq-filter (lambda (s) (string-prefix-p "--share=" s)) command)
                       '("--share=/work/")))
        (should-not (member "--nesting" command)) (should (equal (car (last command)) "--"))))))
(ert-deftest lc-compilation-shell-quoting ()
  (cl-letf (((symbol-function 'lc-guix-command) (lambda (_) '("guix" "shell" "-m" "/work/a b.scm" "--")))
            ((symbol-function 'lc--manifest) (lambda () "/work/a b.scm"))
            ((symbol-function 'lc-workspace-root) (lambda () "/work/")))
    (let (seen)
      (lc-wrap-compilation (lambda (cmd &rest _) (setq seen cmd)) "printf '%s' \"a b\"")
      (should (string-match-p "a\\\\ b.scm\\|'/work/a b.scm'" seen))
      (should (string-match-p "guix shell" seen)))))
(ert-deftest lc-headless-prompts-fail-before-waiting ()
  (let ((noninteractive nil) called)
    (cl-letf (((symbol-function 'lc-input-frames) (lambda () nil)))
      (should-error (lc-guard-input (lambda () (setq called t))) :type 'inhibited-interaction)
      (should-not called))))
(ert-deftest lc-reader-depth-visible-during-questions ()
  (let ((noninteractive t))
    (should (lc-guard-input (lambda () lc--input-reading)))))
(ert-deftest lc-dummy-frame-is-not-input ()
  (cl-letf (((symbol-function 'frame-live-p) (lambda (_) t))
            ((symbol-function 'frame-initial-p) (lambda (_) t)))
    (should-not (lc-input-frame-p 'dummy))))
(ert-deftest lc-file-work-not-logs ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/user.txt") (insert "edit")
    (should (lc-user-work-p (current-buffer))))
  (with-temp-buffer
    (special-mode) (let ((inhibit-read-only t)) (insert "diagnostic"))
    (should-not (lc-user-work-p (current-buffer)))))
(ert-deftest lc-save-explicit-set-only ()
  (let ((a (generate-new-buffer "file-a")) (b (generate-new-buffer "file-b")) saved)
    (unwind-protect
        (progn
          (dolist (buf (list a b))
            (with-current-buffer buf (setq buffer-file-name "/tmp/test") (insert "edit")))
          (cl-letf (((symbol-function 'save-buffer) (lambda (&rest _) (push (current-buffer) saved))))
            (lc-save-frame-work (list a)))
          (should (equal saved (list a))))
      (dolist (buf (list a b)) (with-current-buffer buf (set-buffer-modified-p nil)) (kill-buffer buf)))))
(ert-deftest lc-save-failure-propagates ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/user.txt") (insert "edit")
    (cl-letf (((symbol-function 'save-buffer) (lambda (&rest _) (error "disk full"))))
      (should-error (lc-save-frame-work (list (current-buffer)))))))
(ert-deftest lc-guix-add-message-valid-and-versionless ()
  (should (equal (lc-guix-message-from-diff
                  '("+++ gnu/packages/test.scm" "@@ -0,0 +1 @@" "+(define-public rust-test-1.2 (package))"))
                 "gnu: Add rust-test@1.2.\n\n* gnu/packages/test.scm (rust-test-1.2): New variable.\n"))
  (should-not (string-match-p "nil" (lc-guix-message-from-diff
                                    '("+++ file.scm" "@@ -0,0 +1 @@" "+(define-public foo (package))")))))
(ert-deftest lc-guix-commit-rejects-removals-and-multiple-forms ()
  (should-not (lc-guix-message-from-diff '("+++ file.scm" "@@ -1 +1 @@" "-old" "+(define-public foo (package))")))
  (should-not (lc-guix-message-from-diff '("+++ file.scm" "@@ -0,0 +1 @@" "+(define-public foo (package)) (other)"))))
(ert-deftest lc-build-dir-cancel-cannot-delete-or-rename ()
  (cl-letf (((symbol-function 'file-directory-p) (lambda (_) t))
            ((symbol-function 'file-exists-p) (lambda (_) t))
            ((symbol-function 'yes-or-no-p) (lambda (_) nil))
            ((symbol-function 'delete-directory) (lambda (&rest _) (ert-fail "deleted")))
            ((symbol-function 'rename-file) (lambda (&rest _) (ert-fail "renamed"))))
    (should-error (guix-ensure-drv-0-directory "/tmp/guix-build-name.drv-3/sub") :type 'user-error)))
