;;; test-init.el --- Actual Guix/PGTK init with isolated Org fixtures -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
;; Batch failures print a backtrace. Interactive daemon tests must report errors,
;; not open the debugger recursively on its invisible initial frame.
(setq debug-on-error noninteractive native-comp-enable-subr-trampolines nil)
(defvar lc-integration-source (expand-file-name "../" (file-name-directory load-file-name)))
(make-directory (expand-file-name "cache" lc-integration-source) t)
(defvar lc-integration-root (make-temp-file (expand-file-name "cache/test-init-" lc-integration-source) t))
(dolist (file '("early-init.el" "init.el" "defaults.el"))
  (copy-file (expand-file-name file lc-integration-source) (expand-file-name file lc-integration-root)))
(dolist (dir '("lisp" "user-lisp" "vendor" "assets"))
  (make-symbolic-link (expand-file-name dir lc-integration-source) (expand-file-name dir lc-integration-root)))
(setq lc-config-root (file-name-as-directory lc-integration-root)
      ;; Org Mem intentionally excludes hidden ancestor paths. Test documents
      ;; therefore live outside ~/.config; only this test's config/state live here.
      lc-real-home (file-name-as-directory (make-temp-file "/tmp/lc-org-fixture-" t))
      user-emacs-directory lc-config-root)
(dolist (dir '("doc/org-agenda" "doc/org-roam" "doc/org/daily"))
  (make-directory (expand-file-name dir lc-real-home) t))
(with-temp-file (expand-file-name "doc/org-agenda/agenda.org" lc-real-home)
  (insert "* TODO Fixture reminder\nDEADLINE: <2030-01-01 Tue>\n"))
(with-temp-file (expand-file-name "doc/org-roam/note.org" lc-real-home)
  (insert ":PROPERTIES:\n:ID: lc-fixture-node\n:END:\n#+title: Fixture note\n\nSynthetic test data.\n"))
(defvar lc-integration-start (current-time))
(load (expand-file-name "early-init.el" lc-integration-root) nil t)
(load (expand-file-name "init.el" lc-integration-root) nil t)
(defvar lc-startup-features (copy-sequence features)
  "Exact post-init feature snapshot, before activation tests intentionally load apps.")
(princ (format "INIT_SECONDS=%.3f\n" (float-time (time-subtract (current-time) lc-integration-start))))
(ert-deftest lc-original-solarized-implementation ()
  ;; The original package is color-theme-solarized. The unrelated solarized-theme
  ;; package shares a library filename but has different theme names/settings.
  (should (memq 'solarized custom-enabled-themes))
  (should (eq frame-background-mode 'light))
  (should (locate-library "solarized-definitions"))
  (should-not (memq 'solarized-light custom-enabled-themes)))
(ert-deftest lc-real-org-tree-and-services ()
  (should (string-prefix-p (file-truename (expand-file-name "vendor/org/lisp" lc-integration-source))
                           (file-truename (locate-library "org"))))
  (should (timerp org-notify-timer))
  (should org-mem-updater-mode) (should org-node-cache-mode)
  (should-not (fboundp 'lc-existing-org-paths))
  (should-not (advice-member-p 'lc-existing-org-paths 'org-mem--truenames-and-attrs)))
(ert-deftest lc-startup-does-not-open-applications ()
  (dolist (feature '(mu4e agent-shell emms elfeed lsp-mode dap-mode jupyter org-latex-preview))
    (should-not (memq feature lc-startup-features)))
  (dolist (feature '(xenops gptel ebdb kiwix)) (should-not (memq feature lc-startup-features))))
(ert-deftest lc-reminders-parse-fixture-with-unchanged-paths ()
  (let ((before (copy-sequence org-agenda-files)))
    ;; Future deadline avoids desktop notifications; the normal scanner still runs.
    (org-notify-process)
    (should (equal org-agenda-files before))
    (should (file-exists-p (expand-file-name "doc/org-agenda/agenda.org" lc-real-home)))))
(ert-deftest lc-capture-target-paths-are-usable ()
  (require 'org-capture)
  ;; Org documents templates as (KEY DESCRIPTION TYPE TARGET TEMPLATE ...).
  ;; These keys use file targets; i/j/q deliberately use org-node functions instead.
  ;; File targets are (file FILE), (file+headline FILE HEADLINE), or
  ;; (file+olp+datetree FILE ...). Their FILE slot may be a string or callable.
  (dolist (key '("n" "g" "c" "m" "p" "L" "w"))
    (pcase (assoc key org-capture-templates)
      (`(,_key ,_description ,_type (,target-kind ,file . ,_target-options) . ,_template-options)
       (should (memq target-kind '(file file+headline file+olp+datetree)))
       (should (string-prefix-p lc-real-home (org-capture-expand-file file))))
      (_ (ert-fail (format "Expected a documented file target for capture key %s" key))))))
(ert-deftest lc-gui-options-not-reapplied-on-feature-load ()
  (let ((original (default-value 'line-spacing)))
    (unwind-protect
        (progn (customize-set-variable 'line-spacing .37)
               (require 'lc-media) (require 'lc-org)
               (should (= (default-value 'line-spacing) .37)))
      (customize-set-variable 'line-spacing original))))
(ert-deftest lc-toolbar-global-context-and-renderer ()
  (with-temp-buffer
    (setq major-mode 'mu4e-view-mode)
    (lc-buffer-toolbar)
    (should (eq (lookup-key tool-bar-map [ripgrep]) 'consult-ripgrep))
    (should (eq (lookup-key tool-bar-map [reply]) 'mu4e-compose-reply))
    (let ((text (window-tool-bar-string))) (should (stringp text)))))
(ert-deftest lc-trust-and-removals ()
  (should org-confirm-babel-evaluate)
  ;; Custom's saved-value property is a list containing the saved expression.
  ;; Do not load AUCTeX just to inspect a literal command preference at startup.
  (should (equal (get 'LaTeX-command 'saved-value) '("lualatex")))
  (should (equal (cdr (assoc "/friendly-machines.com/Archive" lc-mail-shortcuts)) ?a))
  (let ((keys (mapcar #'cdr lc-mail-shortcuts)))
    (should (= (length keys) (length (delete-dups (copy-sequence keys)))))))
(ert-deftest lc-node-indexes-fixture ()
  (let ((limit (+ (float-time) 10)))
    (while (and (< (float-time) limit) (not (org-mem-entry-by-id "lc-fixture-node")))
      (accept-process-output nil .1)))
  (should (org-mem-entry-by-id "lc-fixture-node")))
