;;; test-features.el --- Activate real packages without external user services -*- lexical-binding: t; -*-
;; Load after test-init.el. It supplies a fresh config, synthetic Org data and
;; no private credentials. Tests mock only process creation/permissions where
;; needed, not package parsing/indexing behavior or production data paths.
(require 'ert)
(require 'cl-lib)
;; Bindings in test bodies must refer to the libraries' dynamic state, not
;; accidentally lexical variables introduced before those libraries are loaded.
(require 'lc-preview)
(require 'nntp)
(require 'network-stream)
(ert-deftest lc-agent-public-prefix-and-constructor ()
  (require 'agent-shell)
  (require 'agent-shell-loki)
  (should (eq agent-shell-command-prefix #'lc-agent-command-prefix))
  (should-not agent-shell-text-file-capabilities)
  (dolist (function '(agent-shell--make-acp-client agent-shell--build-command-for-execution))
    ;; No configuration advice is allowed on these private package functions.
    (advice-mapc (lambda (advice _properties)
                  (when (and (symbolp advice) (string-prefix-p "lc-" (symbol-name advice)))
                    (ert-fail (format "Private interception remains: %s / %s" function advice))))
                function))
  (let ((agent-shell-loki-acp-command '("/adapter/loki-acp")) constructor-arguments)
    (cl-letf (((symbol-function 'lc-guix-command)
               (lambda (kind) (should (eq kind 'agent)) '("guix" "shell" "--container" "--")))
              ((symbol-function 'my/loki-process-environment) (lambda () '("OPENAI_API_KEY=fixture-only")))
              ((symbol-function 'acp-make-client)
               (lambda (&rest arguments) (setq constructor-arguments arguments) 'fixture-client)))
      (should (eq (agent-shell-loki-make-client :buffer (current-buffer)) 'fixture-client))
      (should (equal (plist-get constructor-arguments :command) "guix"))
      (should (equal (plist-get constructor-arguments :command-params)
                     '("shell" "--container" "--" "/adapter/loki-acp"))))))
(ert-deftest lc-babel-public-autoloads ()
  (dolist (language '(python shell dot gnuplot plantuml))
    (let ((command (intern (format "org-babel-execute:%s" language))))
      (should (fboundp command))))
  (should-not (advice-member-p 'lc-babel-load-backend 'org-babel-execute-src-block))
  (should org-confirm-babel-evaluate))
(ert-deftest lc-mathml-conversion-and-source-safety ()
  (require 'lc-mathml)
  (should (equal (lc-mathml-latex '(mroot nil (mi nil "x") (mn nil "3"))) "\\sqrt[3]{x}"))
  (should (equal (lc-mathml-latex '(munder nil (mo nil "∑") (mi nil "i"))) "\\underset{i}{\\sum }"))
  (should (equal (lc-mathml-latex '(mfenced ((open . "[") (close . "]")) (mi nil "x") (mi nil "y")))
                 "\\left[x,y\\right]"))
  (should (equal (lc-mathml-latex '(mtable nil (mtr nil (mtd nil (mn nil "1")) (mtd nil (mn nil "2")))))
                 "\\begin{matrix}1 & 2\\end{matrix}"))
  (should-not (string-match-p "\\\\input" (lc-mathml-latex '(mi nil "\\input{private}")))))
(ert-deftest lc-mathml-queue-marker-and-cached-completion ()
  (require 'lc-mathml)
  ;; Load only the library; replace its PUBLIC renderer for this queue-contract test.
  (require 'org-latex-preview)
  (with-temp-buffer
    (let ((lc--preview-active-buffer nil) observed)
      (insert "before ")
      (lc-shr-math '(math nil (mi nil "x")))
      (goto-char (point-min)) (insert "prefix ")
      (cl-letf (((symbol-function 'org-latex-preview-place)
                 (lambda (_backend entries _offsets _preamble)
                   (setq observed entries) nil)))
        (lc-preview-drain (current-buffer)))
      ;; Public Org entries are (BEGIN END SOURCE). The moving markers must have
      ;; followed the insertion; no stale original integer position is permitted.
      (pcase observed
        (`((,begin ,end ,source)) (should (equal (buffer-substring begin end) source)))
        (_ (ert-fail "Expected one explicit preview entry")))
      (should-not lc--preview-active-buffer)
      (should-not lc--preview-queue))))
(ert-deftest lc-mathml-async-finish-hook ()
  (require 'lc-mathml) (require 'org-latex-preview)
  (with-temp-buffer
    (let ((lc--preview-active-buffer nil))
      (lc-shr-math '(math nil (mi nil "x")))
      (cl-letf (((symbol-function 'org-latex-preview-place) (lambda (&rest _) '(fixture-job))))
        (lc-preview-drain (current-buffer)))
      (should (eq lc--preview-active-buffer (current-buffer)))
      (lc-preview-finished 0 nil (list :org-buffer (current-buffer)))
      (should-not lc--preview-active-buffer))))
(ert-deftest lc-mu4e-settings-without-starting-mail ()
  (require 'mu4e)
  (should-not (and (boundp 'mu4e--update-timer) mu4e--update-timer))
  (should (equal mu4e-update-interval 240))
  (should (eq mail-user-agent 'mu4e-user-agent))
  (should (equal (mu4e-context-name (car mu4e-contexts)) "friendly-machines.com"))
  (should-not (featurep 'ebdb)))
(ert-deftest lc-publishing-excludes-private-filenames ()
  (require 'ox-publish)
  ;; Org publishing records are (PROJECT-NAME . OPTION-PLIST).
  (pcase-let* ((`(,_project-name . ,options) (assoc "friendly-machines.com" org-publish-project-alist))
               (exclude (plist-get options :exclude)))
    (dolist (name '("entry-private.org" "entry-confidential.org" "entry-internal.org"))
      (should (string-match-p exclude name)))
    (should-not (string-match-p exclude "entry-public.org"))))
(ert-deftest lc-native-jupyter-allocation-retained ()
  (require 'jupyter)
  (should (string-match-p "/jupyter-env\\.el" (symbol-file 'jupyter-session-with-random-ports 'defun)))
  (should-not (featurep 'lc-jupyter-compat)))
(ert-deftest lc-noter-native-functions-and-public-integration ()
  (require 'org-noter) (require 'lc-noter-compat)
  (should (string-match-p "/org-noter-core\\.el" (symbol-file 'org-noter--get-location-left 'defun)))
  (should (string-match-p "/org-noter-core\\.el" (symbol-file 'org-noter-set-start-location 'defun)))
  (should (fboundp 'org-noter-insert-precise-note)))
(ert-deftest lc-emms-import-is-not-library-load-side-effect ()
  (require 'emms)
  (should-not lc--music-imported)
  (should (equal emms-player-list '(emms-player-mpv)))
  (let ((lc--music-imported nil) (lc-music-directory (make-temp-file "/tmp/lc-music-" t)) (imports 0))
    (unwind-protect
        (cl-letf (((symbol-function 'emms-add-directory-tree) (lambda (_) (cl-incf imports))))
          (lc-emms-import-once) (lc-emms-import-once) (should (= imports 1)))
      (delete-directory lc-music-directory t))))
(ert-deftest lc-registered-actions-are-real-commands ()
  ;; Load definitions, not application services, before checking the shared
  ;; action registry's documented COMMAND field.
  (dolist (library '(mu4e agent-shell emms mediainfo-mode magit git-rebase gnus-sum gnus-art))
    (require library))
  (maphash (lambda (id action)
             (let ((command (plist-get action :command)))
               (unless (commandp command)
                 (ert-fail (format "Action %s points to a non-command: %s" id command)))))
           lc-actions))
(ert-deftest lc-news-starttls-required ()
  (require 'lc-news)
  (let ((nntp-address "fixture.invalid") (nntp-port-number 119) parameters)
    (cl-letf (((symbol-function 'open-network-stream)
               (lambda (_name _buffer _host _port &rest arguments) (setq parameters arguments))))
      (lc-nntp-starttls (current-buffer)))
    (should (eq (plist-get parameters :type) 'starttls))))
